# Используем официальный образ Node.js на Alpine Linux
FROM node:22-alpine

# Создаём рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json (если есть)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

